### ISSUE TITLE
Using with Auto Expire and MX Notify Control

### ISSUE THREAD

**Issue by frankharrison-wj** [caddis/scheduled-trigger#6]
I'm trying to use this with Auto Expire (https://devot-ee.com/add-ons/auto-expire) and MX Notify Control (https://devot-ee.com/add-ons/mx-notify-control). When an entry expires, Auto Expire kicks in and changes its status to "Review". I need Scheduled Trigger to then call the entry_submission_end hook so that MX Notify Control detects the status change and sends out an email.

When I add a new entry with an expiration date set, that entry does appear in Scheduled Trigger's Queue. When it expires, Auto Expire correctly changes its status to "Review". If I call Scheduled Trigger's cron URL, the entry disappears from the queue and goes onto the log as expected. But MX Notify Control doesn't get triggered.

If I change the status manually on the entry to "review", MX Notify Control does work. But for some reason it's not working when done via Auto Expire and Scheduled Trigger. I've disabled all other extensions but that doesn't seem to help.

Any idea what might be the problem?

Thanks loads – looks like a great extension!

**Comment by leigeber** [comment]
Just to confirm on the Scheduled Trigger settings page you have the "entry_submission_end" hook checked as well as the relevant channels? To be sure, can you save that page again even if everything looked fine by default, want to make sure something isn't off there. From what you described since MX Notify Control appears to listen to the correct hook it should work.

**Comment by frankharrison-wj** [comment]
Yes that was how it was set up. This morning though I took a different approach: I hacked Auto Expire to send out an email when it changes the status on an expiring entry. Bit dirty but means I'm using one rather than three extensions to achieve this, which feels a bit safer in the long run. Thanks for your response though. Might still use your extension to clear caches...
